### ISSUE TITLE
Menge?

### ISSUE THREAD

**Issue by marcvs** [tdussa/Rezepte#1]
Zutaten für *1* Liter
[...]
1.2 Liter Wasser

Die Frage ist wohl: Bei welchem Druck passt das in meine 1l Flasche ? 
:)

**Comment by tdussa** [comment]
Ach, da ist Verlust mit reingerechnet... Wissenschon, bisserl was verdampft, bisserl was bleibt im Trester, bisserl was verkippt man... XD
